config/routes.rb
Rails.application.routes.draw do
  root to: 'words#index'
  resources :words
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:name, :checked_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyDictionaryApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/words/_form.html.haml
= form_for @word do |f|
  - if @word.errors.any?
    #error_explanation
      %h2= "#{pluralize(@word.errors.count, "error")} prohibited this word from being saved:"
      %ul
        - @word.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label "単語名"
    = f.text_field :name
  .field

  .actions
    = f.submit 'Save'

app/views/words/edit.html.haml
%h1 Editing word

= render 'form'

= link_to 'Show', @word
\|
= link_to 'Back', words_path

app/views/words/index.html.haml
%h1 Listing words

%table
  %thead
    %tr
      %th Name
      %th Checked count
      %th
      %th
      %th

  %tbody
    - @words.each do |word|
      %tr
        %td= word.name
        %td= word.checked_count
        %td= link_to 'Show', word
        %td= link_to 'Edit', edit_word_path(word)
        %td= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Word', new_word_path

app/views/words/new.html.haml
%h1 New word

= render 'form'

= link_to 'Back', words_path

app/views/words/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @word.name
%p
  %b Checked count:
  = @word.checked_count

= link_to 'Edit', edit_word_path(@word)
\|
= link_to 'Back', words_path